# Generated by Django 5.2.7 on 2025-10-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_token', models.CharField(max_length=64, unique=True)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_session_url', models.TextField(blank=True, null=True)),
                ('items', models.JSONField(default=list)),
                ('total_cents', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price_cents', models.IntegerField(help_text='Price in cents (e.g., $5.00 -> 500)')),
            ],
        ),
    ]
